name: Build test

on:
  push:
    branches:
      - feat/add_build_test

jobs:
  # build-emu-simv:
  #   runs-on: [ self-hosted, sz-open ]

  #   strategy:
  #     matrix:
  #       scenario: [ 'emu', 'simv' ]
  #       config-flag: [ '-N small -L small', '-N full -L full' ]
  #       other-flag: [ '', '-ld', '-ldn']
    
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v4
  #       with:
  #         submodules: 'false'
  #     - name: Init project
  #       run: xmake init

  #     - name: Build test (emu)
  #       if: matrix.scenario == 'emu'
  #       run:
  #         if [ "${{ matrix.scenario }}" == "emu" ]; then
  #           EXTRA_FLAGS="-j64"
  #         else
  #           EXTRA_FLAGS=""
  #         fi
  #         xmake ${{ matrix.scenario }} ${{ matrix.config-flag }} ${{ matrix.other-flag }} $EXTRA_FLAGS

  # build-with-custom-dir:
  #   runs-on: [ self-hosted, sz-open ]

  #   strategy:
  #     matrix:
  #       scenario: [ 'emu', 'simv' ]
  #       flags: [ '', '--build_dir=./build_custom', '--sim_dir=./sim_custom', '--build_dir=./build_custom --sim_dir=./sim_custom' ]
  #       use-env-dir: [ 'true', 'false' ]
  #       exclude:
  #         - flags: '--build_dir=./build_custom'
  #           use-env-dir: 'true'
  #         - flags: '--sim_dir=./sim_custom'
  #           use-env-dir: 'true'
  #         - flags: '--build_dir=./build_custom --sim_dir=./sim_custom'
  #           use-env-dir: 'true'
  #         - flags: ''
  #           use-env-dir: 'false'

  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v4
  #       with:
  #         submodules: 'false'
  #     - name: Init project
  #       run: xmake init

  #     - name: Build test
  #       run:
  #         if [ "${{ matrix.scenario }}" == "emu" ]; then
  #           EXTRA_FLAGS="-j64"
  #         else
  #           EXTRA_FLAGS=""
  #         fi

  #         if [ "${{ matrix.use-env-dir }}" == "true" ]; then
  #           export BUILD_DIR=./build_custom
  #           export SIM_DIR=./sim_custom
  #         fi

  #         source /nfs/share/home/zhengchuyu/verilua.sh
  #         xmake ${{ matrix.scenario }} -N small -L small ${{ matrix.flags }} $EXTRA_FLAGS

  build-jar:
    runs-on: [ self-hosted, sz-open ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: false
      - name: Init project
        run: xmake init

      - name: Build jar
        run: xmake comp
