name: Weely LN Release
description: |
  This workflow is triggered on a schedule or manually to run the Weely LN Release Job.
  It is designed to run on a self-hosted runner tagged with 'sz-open'.

on:
  workflow_dispatch: # Enable manual web testing
  # push:
  #   branches: [main]
  schedule:
    # run at 21:00 UTC (5:00 UTC+8) on Wednesday
    - cron: '0 21 * * 2'
    # run every 5 minutes for testing purposes
    # - cron: '*/5 * * * *'


jobs:
  run:
    name: Weely LN Release Job
    runs-on: [self-hosted, sz-open] 
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show time
        run: |
          echo "Running Weely LN Release Job"
          echo "Time: $(date)"

      - name: Init project
        run: xmake init
        
      - name: Make release
        run: ./scripts/release/release.sh 

      - name: Move release files
        run: |
          LATEST_TAR=$(ls -t release_*.tar.gz 2>/dev/null | head -1)
          if [ -z "$LATEST_TAR" ]; then
            echo "Release tarball not found after release, aborting."
            exit 1
          fi
          echo "Release successful, found $LATEST_TAR"
          mv "$LATEST_TAR" /nfs/share/LN-release/

      - name: Cleanup work dir
        if: always()
        run: |
          echo "Cleaning up workspace: $GITHUB_WORKSPACE"
          if [[ -z "$GITHUB_WORKSPACE" || "$GITHUB_WORKSPACE" == "/" ]]; then
            echo "ERROR: GITHUB_WORKSPACE is invalid, aborting cleanup."
            exit 1
          fi
          if [ ! -d "$GITHUB_WORKSPACE/.git" ]; then
            echo "ERROR: Not a git repo, aborting cleanup."
            exit 1
          fi
          rm -rf "$GITHUB_WORKSPACE"