name: Weekly LN EDA Release
description: |
  This workflow is triggered on a schedule or manually to run the Weely LN EDA Release Job.
  It is designed to run on a self-hosted runner tagged with 'sz-open'.

on:
  workflow_dispatch: # Enable manual release
  # push:
  #   branches: [main]
  schedule:
    # run at 21:00 UTC (5:00 UTC+8) on Monday
    - cron: '0 21 * * 0'
    # run at 21:00 UTC (5:00 UTC+8) on Wednesday
    - cron: '0 21 * * 2'
    # run at 21:00 UTC (5:00 UTC+8) on Friday
    - cron: '0 21 * * 4'

jobs:
  run:
    name: Weekly LN EDA Release
    runs-on: [self-hosted, sz-open] 
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show time
        run: |
          echo "Running Weekly LN EDA Release"
          echo "Time: $(date)"

      - name: Init project
        run: xmake init
      
      - name: Make LN release
        run: ./scripts/release/ci-release.sh ST_Single_Core

      - name: Move LN release
        run: |
          LATEST_TAR=$(ls -t Release_*_Core.tar.gz 2>/dev/null | head -3)
          if [ -z "$LATEST_TAR" ]; then
            echo "Release tarball not found after release, aborting."
            exit 1
          fi
          echo "Release successful, found $LATEST_TAR"
          for f in $LATEST_TAR; do
            mv "$f" /nfs/share/LN-release/
          done

      - name: Build LinkNan jar from origin/main
        run: |
          xmake comp
          date_str=$(date +"%Y%m%d")
          ln_commit=$(git rev-parse --short HEAD)
          mv "$GITHUB_WORKSPACE/build/linknan.test.jar" \
          "$GITHUB_WORKSPACE/release_ln_${date_str}_${ln_commit}.jar"

      - name: Move LinkNan jar
        run: |
          JAR_FILE=$(ls -t release_ln_*.jar 2>/dev/null | head -1)
          if [ -z "$JAR_FILE" ]; then
            echo "Jar file not found after build, aborting."
            exit 1
          fi
          echo "Jar file found: $JAR_FILE"
          mv "$JAR_FILE" /nfs/share/LN-release/

      - name: Cleanup work dir
        if: always()
        run: |
          echo "Cleaning generated files inside workspace..."
          rm -rf build build.bak release_* Release_* out .xmake sim dependencies