name: Weely LN Release
description: |
  This workflow is triggered on a schedule or manually to run the Weely LN Release Job.
  It is designed to run on a self-hosted runner tagged with 'sz-open'.

on:
  workflow_dispatch: # Enable manual web testing
  # push:
  #   branches: [main]
  schedule:
    # run at 21:00 UTC (5:00 UTC+8) on Wednesday
    - cron: '0 21 * * 2'
    # run every 5 minutes for testing purposes
    # - cron: '*/5 * * * *'


jobs:
  run:
    name: Weely LN Release Job
    runs-on: [self-hosted, sz-open] 
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show time
        run: |
          echo "Running Weely LN Release Job"
          echo "Time: $(date)"

      - name: Init project
        run: xmake init
        
      - name: Make LN release
        run: ./scripts/release/release.sh 

      - name: Move LN release
        run: |
          LATEST_TAR=$(ls -t release_*.tar.gz 2>/dev/null | head -1)
          if [ -z "$LATEST_TAR" ]; then
            echo "Release tarball not found after release, aborting."
            exit 1
          fi
          echo "Release successful, found $LATEST_TAR"
          mv "$LATEST_TAR" /nfs/share/LN-release/

      - name: Build nanhu jar from origin/main
        run: |
          set -e
          nh_dir="$GITHUB_WORKSPACE/dependencies/nanhu"
          cd "$nh_dir"

          git fetch origin
          git checkout -B __tmp_build origin/main

          echo "init nanhu dependencies"
          make init

          echo "Build jar..."
          export NOOP_HOME="$nh_dir"
          make test-jar

          nanhu_commit=$(git rev-parse --short HEAD)
          date_str=$(date +"%Y%m%d")

          mv "$nh_dir/out/xiangshan/test/assembly.dest/out.jar" \
          "$GITHUB_WORKSPACE/release_${date_str}_${nanhu_commit}.jar"

      - name: Move nanhu jar
        run: |
          JAR_FILE=$(ls -t release_*.jar 2>/dev/null | head -1)
          if [ -z "$JAR_FILE" ]; then
            echo "Jar file not found after build, aborting."
            exit 1
          fi
          echo "Jar file found: $JAR_FILE"
          mv "$JAR_FILE" /nfs/share/LN-release/

      - name: Cleanup work dir
        if: always()
        run: |
          echo "Cleaning generated files inside workspace..."
          rm -rf build build.bak release_* out .xmake sim dependencies